In [ ]:
import os
import pickle
import pandas as pd
import numpy as np
from src.calculate_results import (
    append_meta_data, get_all_accuracy, calculate_all_metrics
)

In [4]:
ROOT_DIR = os.getcwd()
DATA_DIR = os.path.join(ROOT_DIR, "..", "data")
RESULTS_DIR = os.path.join(ROOT_DIR, "..", "results")
meta = pd.read_csv(os.path.join(DATA_DIR, "participants.tsv"), sep="\t")

AD vs. CN task

In [5]:
# Load all the band results
with open(os.path.join(RESULTS_DIR, "bands/C_A/_freq_alpha/C_A/all_results.pkl"), "rb") as f:
    alpha_ad = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/C_A/_freq_beta/C_A/all_results.pkl"), "rb") as f:
    beta_ad = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/C_A/_freq_delta/C_A/all_results.pkl"), "rb") as f:
    delta_ad = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/C_A/_freq_gamma/C_A/all_results.pkl"), "rb") as f:
    gamma_ad = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/C_A/_freq_theta/C_A/all_results.pkl"), "rb") as f:
    theta_ad = pickle.load(f)

In [6]:
# Append subject metadata to results
alpha_ad = append_meta_data(alpha_ad, meta)
beta_ad = append_meta_data(beta_ad, meta)
delta_ad = append_meta_data(delta_ad, meta)
gamma_ad = append_meta_data(gamma_ad, meta)
theta_ad = append_meta_data(theta_ad, meta)

In [7]:
# Get test accuracies
alpha_acc = pd.DataFrame(get_all_accuracy(alpha_ad))
beta_acc = pd.DataFrame(get_all_accuracy(beta_ad))
delta_acc = pd.DataFrame(get_all_accuracy(delta_ad))
gamma_acc = pd.DataFrame(get_all_accuracy(gamma_ad))
theta_acc = pd.DataFrame(get_all_accuracy(theta_ad))

In [8]:
# Calculate accuracy mean and std
print("Alpha band accuracy:", alpha_acc["test_accuracy"].mean(), "±", alpha_acc["test_accuracy"].std())
print("Beta band accuracy:", beta_acc["test_accuracy"].mean(), "±", beta_acc["test_accuracy"].std())
print("Delta band accuracy:", delta_acc["test_accuracy"].mean(), "±", delta_acc["test_accuracy"].std())
print("Gamma band accuracy:", gamma_acc["test_accuracy"].mean(), "±", gamma_acc["test_accuracy"].std())
print("Theta band accuracy:", theta_acc["test_accuracy"].mean(), "±", theta_acc["test_accuracy"].std())

Alpha band accuracy: 0.6833356137172534 ± 0.29533122054090877
Beta band accuracy: 0.6059532427730469 ± 0.26057862635123336
Delta band accuracy: 0.6827482476830482 ± 0.25118512408412097
Gamma band accuracy: 0.5039497853471683 ± 0.22706501128580395
Theta band accuracy: 0.6160260714017428 ± 0.2020482752771891

In [23]:
# Calculate all metrics
alpha_metrics = pd.DataFrame([calculate_all_metrics(alpha_ad)])
beta_metrics = pd.DataFrame([calculate_all_metrics(beta_ad)])
delta_metrics = pd.DataFrame([calculate_all_metrics(delta_ad)])
gamma_metrics = pd.DataFrame([calculate_all_metrics(gamma_ad)])
theta_metrics = pd.DataFrame([calculate_all_metrics(theta_ad)])

In [24]:
# Concat metrics for all bands
all_band_metrics = pd.concat([
    delta_metrics,
    theta_metrics,
    alpha_metrics,
    beta_metrics,
    gamma_metrics
], axis=0, ignore_index=True)

# Add band names
all_band_metrics["band"] = ["delta", "theta", "alpha", "beta", "gamma"]
all_band_metrics

,accuracy,f1_score,sensitivity,specificity,roc_auc,confusion_matrix,band
0,0.688005,0.730797,0.774001,0.584107,0.751432,"[[14025, 9986], [6556, 22453]]",delta
1,0.610883,0.640456,0.633424,0.583649,0.661437,"[[14014, 9997], [10634, 18375]]",theta
2,0.692022,0.732588,0.771037,0.596560,0.739276,"[[14324, 9687], [6642, 22367]]",alpha
3,0.604583,0.651275,0.674860,0.519678,0.644458,"[[12478, 11533], [9432, 19577]]",beta
4,0.499774,0.536685,0.529525,0.463829,0.496218,"[[11137, 12874], [13648, 15361]]",gamma

FTD vs. CN task

In [16]:
# Load all the band results
with open(os.path.join(RESULTS_DIR, "bands/F_C/alpha/_fixed_C_F/all_results.pkl"), "rb") as f:
    alpha_ftd = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/F_C/beta/_fixed_C_F/all_results.pkl"), "rb") as f:
    beta_ftd = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/F_C/delta/_fixed_C_F/all_results.pkl"), "rb") as f:
    delta_ftd = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/F_C/gamma/_fixed_C_F/all_results.pkl"), "rb") as f:
    gamma_ftd = pickle.load(f)
with open(os.path.join(RESULTS_DIR, "bands/F_C/theta/_fixed_C_F/all_results.pkl"), "rb") as f:
    theta_ftd = pickle.load(f)

In [17]:
# Append subject metadata to results
alpha_ftd = append_meta_data(alpha_ftd, meta)
beta_ftd = append_meta_data(beta_ftd, meta)
delta_ftd = append_meta_data(delta_ftd, meta)
gamma_ftd = append_meta_data(gamma_ftd, meta)
theta_ftd = append_meta_data(theta_ftd, meta)

In [20]:
# Get test accuracies
alpha_acc = pd.DataFrame(get_all_accuracy(alpha_ftd))
beta_acc = pd.DataFrame(get_all_accuracy(beta_ftd))
delta_acc = pd.DataFrame(get_all_accuracy(delta_ftd))
gamma_acc = pd.DataFrame(get_all_accuracy(gamma_ftd))
theta_acc = pd.DataFrame(get_all_accuracy(theta_ftd))

In [19]:
# Calculate accuracy mean and std
print("Alpha band accuracy:", alpha_acc["test_accuracy"].mean(), "±", alpha_acc["test_accuracy"].std())
print("Beta band accuracy:", beta_acc["test_accuracy"].mean(), "±", beta_acc["test_accuracy"].std())
print("Delta band accuracy:", delta_acc["test_accuracy"].mean(), "±", delta_acc["test_accuracy"].std())
print("Gamma band accuracy:", gamma_acc["test_accuracy"].mean(), "±", gamma_acc["test_accuracy"].std())
print("Theta band accuracy:", theta_acc["test_accuracy"].mean(), "±", theta_acc["test_accuracy"].std())

Alpha band accuracy: 0.6032098862700738 ± 0.2686981539143684
Beta band accuracy: 0.6052927982348663 ± 0.3417752233974602
Delta band accuracy: 0.601790359387031 ± 0.33631976722217316
Gamma band accuracy: 0.6234626925836962 ± 0.37458001323478834
Theta band accuracy: 0.5758336092202136 ± 0.3867508589756887

In [28]:
# Calculate all metrics
alpha_metrics = pd.DataFrame([calculate_all_metrics(alpha_ftd)])
beta_metrics = pd.DataFrame([calculate_all_metrics(beta_ftd)])
delta_metrics = pd.DataFrame([calculate_all_metrics(delta_ftd)])
gamma_metrics = pd.DataFrame([calculate_all_metrics(gamma_ftd)])
theta_metrics = pd.DataFrame([calculate_all_metrics(theta_ftd)])

In [29]:
# Concat metrics for all bands
all_band_metrics = pd.concat([
    delta_metrics,
    theta_metrics,
    alpha_metrics,
    beta_metrics,
    gamma_metrics
], axis=0, ignore_index=True)

# Add band names
all_band_metrics["band"] = ["delta", "theta", "alpha", "beta", "gamma"]
all_band_metrics

,accuracy,f1_score,sensitivity,specificity,roc_auc,confusion_matrix,band
0,0.615459,0.347542,0.251363,0.865812,0.598485,"[[20789, 3222], [12360, 4150]]",delta
1,0.596259,0.232933,0.150454,0.902795,0.502059,"[[21677, 2334], [14026, 2484]]",theta
2,0.611436,0.461175,0.408116,0.751239,0.623012,"[[18038, 5973], [9772, 6738]]",alpha
3,0.624071,0.376285,0.278316,0.861813,0.602375,"[[20693, 3318], [11915, 4595]]",beta
4,0.637200,0.376416,0.268746,0.890550,0.603784,"[[21383, 2628], [12073, 4437]]",gamma